spring:
    datasource:
        url: jdbc:mysql://localhost:3306/p3
        username: rayan
        password: 12345abcde
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
        show-sql: true
        properties:
            hibernate:
                    format_sql: true
