spring:
    datasource:
        url: jdbc:mysql://localhost:3306/p3
        username: "root"
        password: "12345abcde"
        driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
        hibernate:
            ddl-auto: create
            dialect: org.hibernate.dialect.MySQL8Dialect
        show-sql: true
        properties:
            hibernate:
                    format_sql: true
    mvc:
        path-match:
            matching-strategy: ant_path_matcher
jwt:
    secret:
        key: "SECRET_KEY"
    expiration: 1000*60*15
    token-prefix: "Bearer "
    header-string: "Authorization"

server:
    port: 3001
    forward-headers-strategy: framework

spring-doc:
    swagger-ui:
        config-url: "/v3/api-docs/swagger-config"
        url: "/v3/api-docs"